PIAAS1/Web/Models/DocumentViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public enum Categorie { Document, Image }

    public class DocumentViewModel
    {
        [Key]
        public int DocumentId { get; set; }
        public string DocumentName { get; set; }
        public string Path { get; set; }
        public Categorie categorie { get; set; }
        public long Size { get; set; }
        public DateTime DateCreation { get; set; }
        public Project Project { get; set; }
        public int ProjectFK { get; set; }
    }
}

PIAAS1/Web/Controllers/DocumentController.cs
using Domain.Entities;
using Service.Interfaces;
using Service.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using Web.Models;


namespace Web.Controllers
{
    public class DocumentController : Controller
    {
        IDocumentService DS = new DocumentServices();
        IProjectServices PS = new ProjectServices();
        // GET: Document
        public ActionResult Index()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            //redirect to nowhere if not admin
            if (!(User.IsInRole("Admin")))
            {
                return RedirectToAction("Nowhere", "Account");
            }
            var getAll = DS.GetAll().Where(e => e.categorie == Domain.Entities.Categorie.Image);
            return View(getAll);
        }
        public ActionResult IndexDocument()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            //redirect to nowhere if not admin
            if (!(User.IsInRole("Admin")))
            {
                return RedirectToAction("Nowhere", "Account");
            }
            var getAll = DS.GetAll().Where(e => e.categorie == Domain.Entities.Categorie.Document);

            return View(getAll);
        }
        // GET: Document/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Document/Create
        public ActionResult Create(int idProject)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            //redirect to nowhere if not admin
            if (!(User.IsInRole("Team Leader")))
            {
                return RedirectToAction("Nowhere", "Account");
            }
            ViewData["id"] = idProject;
            return View();
        }

        // POST: Document/Create
        [HttpPost]
        public ActionResult Create(int idProject, HttpPostedFileBase file, DocumentViewModel DVM)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            //redirect to nowhere if not admin
            if (!(User.IsInRole("Team Leader")))
            {
                return RedirectToAction("Nowhere", "Account");
            }
            Project P = PS.GetById(idProject);
            Document D = new Document();
            D.DocumentId = DVM.DocumentId;
            D.DocumentName = DVM.DocumentName;
            D.categorie = (Domain.Entities.Categorie)DVM.categorie;
            try
            {
                if (file.ContentLength > 0)
                {

                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Documents/"), fileName);
                    file.SaveAs(path);
                    DVM.Size = file.ContentLength / 1024;
                    D.Path = "~/Content/Documents/" + fileName;
                    D.Size = DVM.Size;
                    D.DateCreation = DateTime.Now;
                    D.ProjectFK = P.ProjectId;
                    ViewBag.Message = "File Uploaded Successfully!!";
                    DS.Add(D);
                    DS.Commit();

                }
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View(DVM);
            }


            return RedirectToAction("Details", "Project", new {id = idProject });

        }
        // GET: Document/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Document/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Document/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Document/Delete/5
        [HttpPost]
        public ActionResult Delete(DocumentViewModel DVM)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            //redirect to nowhere if not admin
            if (!(User.IsInRole("Team Leader")))
            {
                return RedirectToAction("Nowhere", "Account");
            }
            Document D = new Document();
            D.DocumentId = DVM.DocumentId;
            D.DocumentName = DVM.DocumentName;


            DS.Delete(D);
            DS.Commit();
            return RedirectToAction("Index");
        }



    }
}

PIAAS1/Web/Views/Document/Create.cshtml
@model Web.Models.DocumentViewModel


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    IEnumerable<Domain.Entities.Categorie> categorie = ViewData["Cat"] as IEnumerable<Domain.Entities.Categorie>;
    var id = ViewData["id"];

}


@using (Html.BeginForm("Create", "Document", new { idProject = id }, FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="file" name="file" id="file" />
            </div>
        </div>



        <div class="row clearfix">
            <div class="col-sm-12">
                <div class="form-group">
                    <label>Category</label>
                    <br />
                    <label class="fancy-radio">
                        <input type="radio" name="categorie" id="categorie" value="Image" required>
                        <span><i></i>Image</span>
                    </label>
                    <label class="fancy-radio">
                        <input type="radio" name="categorie" id="categorie" value="Document" required>
                        <span><i></i>Document</span>
                    </label>

                    <p id="error-radio"></p>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                    @id
                </div>
            </div>
        </div>
    </div>

}