Web/Models/DocumentViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public enum Categorie { Document, Image }
    public class DocumentViewModel
    {
        [Key]
        public int DocumentId { get; set; }
        public string DocumentName { get; set; }
        public string Path { get; set; }
        public Categorie categorie { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM, yyyy}")]
        public DateTime DateCreation { get; set; }
        public Project Project { get; set; }
        public int ProjectFK { get; set; }
        public int Size { get; set; }
    }
}

Web/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Service.Interfaces;
using Service.Services;
using Web.Models;




namespace Web.Controllers
{
    public class DocumentController : Controller
    {

        IDocumentService DS = new DocumentServices();
        // GET: Document
        public ActionResult Index()
        {
            var getAll = DS.GetAll().Where(e => e.categorie == Domain.Entities.Categorie.Image);

            return View(getAll);
        }

        public ActionResult IndexDocument()
        {
            var getAll = DS.GetAll().Where(e => e.categorie == Domain.Entities.Categorie.Document);

            return View(getAll);
        }
        // GET: Document/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Document/Create
        public ActionResult Create()
        {

            List<string> Categorie = new List<string> { "Document", "Image" };
            ViewData["Categorie"] = new SelectList(Categorie);
            return View();
        }

        // POST: Document/Create
        [HttpPost]
        public ActionResult Create(DocumentViewModel DVM, System.Web.HttpPostedFileBase file)
        {
            Document D = new Document();
            D.DocumentId = DVM.DocumentId;
            D.DocumentName = DVM.DocumentName;
            D.Size = DVM.Size;

            D.categorie = (Domain.Entities.Categorie)DVM.categorie;
            try
            {
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Documents/"), fileName);

                    file.SaveAs(path);
                    D.Path = "~/Content/Documents/" + fileName;
                    ViewBag.Message = "File Uploaded Successfully!!";
                }
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
            D.DateCreation = DateTime.Now;

            DS.Add(D);
            DS.Commit();
            if (DVM.categorie == Web.Models.Categorie.Image)
            {

                return View("Index");
            }

            else
            {
                return View("IndexDocument");
            }
        }

        // GET: Document/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Document/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Document/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Document/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/Controllers/ProjectController.cs
using Domain.Entities;
using Service.Interfaces;
using Service.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;

using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class ProjectController : Controller
    {
        IProjectServices ps = new ProjectServices();
        IUserService us = new UserService();
        TaskServices TS = new TaskServices();

        // GET: Project
        public ActionResult Index()
        {
            var currentUserId = User.Identity.GetUserId();
            int myInt = int.Parse(currentUserId);

            User u = us.GetById(myInt);
            var getAll = ps.GetAll().Where(e => e.TeamFK == u.TeamFK);

            return View(getAll);
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            ProjectViewModel PVM = new ProjectViewModel();
            var pip = ps.GetById(id);
            PVM.ProjectId = pip.ProjectId;
            PVM.ProjectName = pip.ProjectName;
            PVM.Start_Date = pip.Start_Date;
            PVM.End_Date = pip.End_Date;
            PVM.Duration = pip.Duration;
            PVM.etat = (Web.Models.Etat)pip.etat;
            //---------------------------------------
            PVM.Description = pip.Description;
            var currentUserId = User.Identity.GetUserId();
            int myInt = int.Parse(currentUserId);

            User teamlead = us.GetById(myInt);
            //---------------------------------------
            TeamService teamservice = new TeamService();
            Team t = teamservice.GetById(teamlead.TeamFK);
            //--------------------------------------------
            float progress = TS.ProjectProgress(id);

            var T = TS.GetAll().Where(e => e.ProjectFK == id);
            Console.WriteLine(T);
            List<Tasks> tasks = T.ToList();
            ViewData["Tasks"] = tasks;
            ViewData["TeamLead"] = teamlead;
            ViewData["Team"] = t;
            ViewData["Progress"] = progress;


            return View(PVM);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(ProjectViewModel PVM)
        {
            Project P = new Project();
            var currentUserId = User.Identity.GetUserId();
            int myInt = int.Parse(currentUserId);

            User u = us.GetById(myInt);

            if (PVM.Start_Date >= DateTime.Now)
            {




                P.ProjectId = PVM.ProjectId;
                P.ProjectName = PVM.ProjectName;
                P.Description = PVM.Description;
                P.etat = Domain.Entities.Etat.Active;
                P.Duration = (PVM.End_Date - PVM.Start_Date).TotalDays.ToString();
                P.Start_Date = PVM.Start_Date;
                P.End_Date = PVM.End_Date;
                P.TeamFK = u.TeamFK;
                ps.Add(P);
                ps.Commit();

                return RedirectToAction("index");
            }
            else
                ViewBag.Message = "Start date must be greater than Today !";
            return View("Create");



        }

        public ActionResult CreateTest(ProjectViewModel PVM)
        {

            return View();

        }
        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            var pip = ps.GetById(id);
            ProjectViewModel PVM = new ProjectViewModel();
            PVM.ProjectName = pip.ProjectName;
            PVM.Start_Date = pip.Start_Date;
            PVM.End_Date = pip.End_Date;
            PVM.Duration = pip.Duration;
            List<string> Etat = new List<string> { "Pending", "Closed", "Active" };
            ViewData["Etat"] = new SelectList(Etat);

            PVM.Description = pip.Description;
            return View(PVM);

        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ProjectViewModel PVM)
        {
            Project P = ps.GetById(id);
            P.ProjectName = PVM.ProjectName;
            P.Start_Date = PVM.Start_Date;
            P.End_Date = PVM.End_Date;
            //P.Duration = (PVM.End_Date - PVM.Start_Date).TotalDays.ToString();
            P.Description = PVM.Description;
            P.etat = (Domain.Entities.Etat)PVM.etat;
            ps.Update(P);
            ps.Commit();
            return RedirectToAction("Index");
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ProjectViewModel PVM)
        {
            Project p = ps.GetById(id);

            PVM.ProjectId = p.ProjectId;
            PVM.ProjectName = p.ProjectName;
            PVM.Start_Date = p.Start_Date;
            PVM.End_Date = p.End_Date;
            PVM.Duration = p.Duration;
            PVM.Description = p.Description;
            ps.Delete(p);
            ps.Commit();



            return RedirectToAction("Index");

        }
    }
}

Web/Views/Document/Create.cshtml
@model Web.Models.DocumentViewModel


@{


    Layout = "~/Views/Shared/_TeamleaderLayout.cshtml";
}

@using (Html.BeginForm("Create", "Document", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-12">
                    <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Create New Project</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                        <li class="breadcrumb-item">Projects</li>
                        <li class="breadcrumb-item active">Add Project</li>
                    </ul>
                </div>
                <div class="col-lg-6 col-md-4 col-sm-12 text-right">
                    <div class="bh_chart hidden-xs">
                        <div class="float-left m-r-15">
                            <small>Visitors</small>
                            <h6 class="mb-0 mt-1"><i class="icon-user"></i> 1,784</h6>
                        </div>
                        <span class="bh_visitors float-right">2,5,1,8,3,6,7,5</span>
                    </div>
                    <div class="bh_chart hidden-sm">
                        <div class="float-left m-r-15">
                            <small>Visits</small>
                            <h6 class="mb-0 mt-1"><i class="icon-globe"></i> 325</h6>
                        </div>
                        <span class="bh_visits float-right">10,8,9,3,5,8,5</span>
                    </div>
                    <div class="bh_chart hidden-sm">
                        <div class="float-left m-r-15">
                            <small>Chats</small>
                            <h6 class="mb-0 mt-1"><i class="icon-bubbles"></i> 13</h6>
                        </div>
                        <span class="bh_chats float-right">1,8,5,6,2,4,3,2</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="body">

                        @Html.AntiForgeryToken()
                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Project Name" } })
                                    @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
                                    @*<input type="text" class="form-control" placeholder="Project Name *">*@
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control", @placeholder = "Project Name" } })
                                    @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
                                    @*<input type="text" class="form-control" placeholder="Project Name *">*@
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="file" name="file" id="file" />
                                </div>
                            </div>

                        </div>


                        <div class="row clearfix">
                            @*<div class="col-12">
                                    <input type="file" class="dropify">
                                    <div class="mt-3"></div>
                                </div>*@

                            <div class="col-sm-12">
                                <div class="form-group">
                                    @Html.DropDownListFor(model => model.categorie, (SelectList)ViewData["categorie"], "---- SVP selectionnez----", new { htmlAttributes = new { @class = "form-control show-tick" } })
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="mt-4">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                    @ViewBag.Message

                                    <button type="reset" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Index", "Project")'">Cancel</button>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>



}

Web/Views/Document/Index.cshtml
@model IEnumerable<Domain.Entities.Document>

@{
    /**/

    Layout = "~/Views/Shared/_TeamleaderLayout.cshtml";
}



@using (Html.BeginForm())
{

    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-12">
                    <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Projects List</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                        <li class="breadcrumb-item">Projects</li>
                        <li class="breadcrumb-item active">Projects List</li>
                    </ul>
                </div>

            </div>
        </div>
    </div>




    <div class="row clearfix">

        @foreach (var item in Model)
        {


            <div class="col-lg-3 col-md-4 col-sm-12">

                <div class="card">
                    <div class="file">
                        <a href="javascript:void(0);">
                            <div class="hover">

                            </div>

                            <div class="image">

                                <img src="@Url.Content(item.Path)" alt="Image" class="img-fluid" style="height:50px;width:100px;" />
                            </div>
                            <div class="file-name">
                                <p class="m-b-5 text-muted">@Html.DisplayFor(modelItem => item.DocumentName)</p>
                                <small>@Html.DisplayFor(modelItem => item.Size) <span class="date text-muted">@Html.DisplayFor(modelItem => item.DateCreation)</span></small>
                            </div>

                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
}

Web/Views/Document/IndexDocument.cshtml
@model IEnumerable<Domain.Entities.Document>

@{
    /**/

    Layout = "~/Views/Shared/_TeamleaderLayout.cshtml";
}



@using (Html.BeginForm())
{

    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-12">
                    <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Projects List</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                        <li class="breadcrumb-item">Projects</li>
                        <li class="breadcrumb-item active">Projects List</li>
                    </ul>
                </div>
                <div class="col-lg-6 col-md-4 col-sm-12 text-right">
                    <div class="bh_chart hidden-xs">
                        <div class="float-left m-r-15">
                            <small>Visitors</small>
                            <h6 class="mb-0 mt-1"><i class="icon-user"></i> 1,784</h6>
                        </div>
                        <span class="bh_visitors float-right">2,5,1,8,3,6,7,5</span>
                    </div>
                    <div class="bh_chart hidden-sm">
                        <div class="float-left m-r-15">
                            <small>Visits</small>
                            <h6 class="mb-0 mt-1"><i class="icon-globe"></i> 325</h6>
                        </div>
                        <span class="bh_visits float-right">10,8,9,3,5,8,5</span>
                    </div>
                    <div class="bh_chart hidden-sm">
                        <div class="float-left m-r-15">
                            <small>Chats</small>
                            <h6 class="mb-0 mt-1"><i class="icon-bubbles"></i> 13</h6>
                        </div>
                        <span class="bh_chats float-right">1,8,5,6,2,4,3,2</span>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="row clearfix">
        @foreach (var item in Model)
        {

            <div class="col-lg-3 col-md-4 col-sm-12">
                <div class="card">
                    <div class="file">
                        <a href="javascript:void(0);">
                            <div class="hover">

                            </div>
                            <div class="icon">
                                <img src="@Url.Content(item.Path)" alt="Document" class="fa fa-file text-info" style="height:50px;width:100px;" />
                            </div>
                            <div class="file-name">
                                <p class="m-b-5 text-muted">@Html.DisplayFor(modelItem => item.DocumentName)</p>
                                <small>Size: @Html.DisplayFor(modelItem => item.Size) <span class="date text-muted">Created :@Html.DisplayFor(modelItem => item.DateCreation)</span></small>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
}