Web/Models/ProjectViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public enum Etat { Pending, Active, Closed }
    public class ProjectViewModel
    {

        [Key]
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM, yyyy}")]
        public DateTime Start_Date { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM, yyyy}")]
        public DateTime End_Date { get; set; }
        public string Duration { get; set; }
        public string Description { get; set; }
        public Etat etat { get; set; }
        public virtual ICollection<Phase> Phases { get; set; }
        public virtual ICollection<Tasks> Tasks { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public Team Team { get; set; }
        public Client C { get; set; }
        public User TeamLeader { get; set; }
        public int UserFk { get; set; }
        public virtual ICollection<User> TemMembers { get; set; }

    }
}

Web/Controllers/ProjectController.cs
using Domain.Entities;
using Service.Interfaces;
using Service.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;

using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class ProjectController : Controller
    {
        IProjectServices ps = new ProjectServices();
        IUserService us = new UserService();
        TaskServices TS = new TaskServices();

        // GET: Project
        public ActionResult Index()
        {
            var currentUserId = User.Identity.GetUserId();
            int myInt = int.Parse(currentUserId);

            User u = us.GetById(myInt);
            var getAll = ps.GetAll().Where(e => e.TeamFK == u.TeamFK);

            return View(getAll);
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            ProjectViewModel PVM = new ProjectViewModel();
            var pip = ps.GetById(id);
            PVM.ProjectId = pip.ProjectId;
            PVM.ProjectName = pip.ProjectName;
            PVM.Start_Date = pip.Start_Date;
            PVM.End_Date = pip.End_Date;
            PVM.Duration = pip.Duration;
            PVM.etat = (Web.Models.Etat)pip.etat;
            //---------------------------------------
            PVM.Description = pip.Description;
            var currentUserId = User.Identity.GetUserId();
            int myInt = int.Parse(currentUserId);

            User teamlead = us.GetById(myInt);
            //---------------------------------------
            TeamService teamservice = new TeamService();
            Team t = teamservice.GetById(teamlead.TeamFK);
            //--------------------------------------------
            float progress = TS.ProjectProgress(id);

            var T = TS.GetAll().Where(e => e.ProjectFK == id);
            Console.WriteLine(T);
            List<Tasks> tasks = T.ToList();
            ViewData["Tasks"] = tasks;
            ViewData["TeamLead"] = teamlead;
            ViewData["Team"] = t;
            ViewData["Progress"] = progress;


            return View(PVM);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(ProjectViewModel PVM)
        {
            Project P = new Project();
            var currentUserId = User.Identity.GetUserId();
            int myInt = int.Parse(currentUserId);

            User u = us.GetById(myInt);

            if (PVM.Start_Date >= DateTime.Now)
            {




                P.ProjectId = PVM.ProjectId;
                P.ProjectName = PVM.ProjectName;
                P.Description = PVM.Description;
                P.etat = Domain.Entities.Etat.Active;
                P.Duration = (PVM.End_Date - PVM.Start_Date).TotalDays.ToString();
                P.Start_Date = PVM.Start_Date;
                P.End_Date = PVM.End_Date;
                P.TeamFK = u.TeamFK;
                ps.Add(P);
                ps.Commit();

                return RedirectToAction("index");
            }
            else
                ViewBag.Message = "Start date must be greater than Today !";
            return View("Create");



        }

        public ActionResult CreateTest(ProjectViewModel PVM)
        {

            return View();

        }
        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            var pip = ps.GetById(id);
            ProjectViewModel PVM = new ProjectViewModel();
            PVM.ProjectName = pip.ProjectName;
            PVM.Start_Date = pip.Start_Date;
            PVM.End_Date = pip.End_Date;
            PVM.Duration = pip.Duration;
            List<string> Etat = new List<string> { "Pending", "Closed", "Active" };
            ViewData["Etat"] = new SelectList(Etat);

            PVM.Description = pip.Description;
            return View(PVM);

        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ProjectViewModel PVM)
        {
            Project P = ps.GetById(id);
            P.ProjectName = PVM.ProjectName;
            P.Start_Date = PVM.Start_Date;
            P.End_Date = PVM.End_Date;
            //P.Duration = (PVM.End_Date - PVM.Start_Date).TotalDays.ToString();
            P.Description = PVM.Description;
            P.etat = (Domain.Entities.Etat)PVM.etat;
            ps.Update(P);
            ps.Commit();
            return RedirectToAction("Index");
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ProjectViewModel PVM)
        {
            Project p = ps.GetById(id);

            PVM.ProjectId = p.ProjectId;
            PVM.ProjectName = p.ProjectName;
            PVM.Start_Date = p.Start_Date;
            PVM.End_Date = p.End_Date;
            PVM.Duration = p.Duration;
            PVM.Description = p.Description;
            ps.Delete(p);
            ps.Commit();



            return RedirectToAction("Index");

        }
    }
}

Web/Controllers/TaskController.cs
using Domain.Entities;
using Service.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class TaskController : Controller
    {

        TaskServices TS = new TaskServices();


        // GET: Task
        public ActionResult Index()
        {
            var getAll = TS.GetAll();

            return View(getAll);
        }

        // GET: Task/Details/5
        public ActionResult Details(int id)
        {
            var pip = TS.GetById(id);
            TaskViewModel TVM = new TaskViewModel();
            TVM.TaskName = pip.TaskName;
            TVM.Start_Date = pip.Start_Date;
            TVM.End_Date = pip.End_Date;
            TVM.Duration = pip.Duration;
            TVM.Description = pip.Description;
            TVM.Estimation = pip.Estimation;


            return View(TVM);
        }

        // GET: Task/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Task/Create
        [HttpPost]
        public ActionResult Create(TaskViewModel TVM, int idProject)
        {
            Tasks T = new Tasks();

            T.TasksId = TVM.TasksId;
            T.TaskName = TVM.TaskName;
            T.Start_Date = TVM.Start_Date;
            T.End_Date = TVM.End_Date;
            T.Estimation = TVM.Estimation;
            T.Status = Domain.Entities.status.Done;
            T.Description = TVM.Description;
            T.Duration = TVM.Duration;
            T.ProjectFK = idProject;

            TS.Add(T);
            TS.Commit();
            return RedirectToAction("Details", "Project", new { id = idProject });
        }

        // GET: Task/Edit/5
        public ActionResult Edit(int id)
        {
            var pip = TS.GetById(id);
            TaskViewModel TVM = new TaskViewModel();
            TVM.TaskName = pip.TaskName;
            TVM.Start_Date = pip.Start_Date;
            TVM.End_Date = pip.End_Date;
            TVM.Duration = pip.Duration;
            TVM.Description = pip.Description;
            TVM.Estimation = pip.Estimation;






            return View(TVM);
        }

        // POST: Task/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TaskViewModel TVM)
        {
            Tasks T = TS.GetById(id);
            T.TaskName = TVM.TaskName;
            T.Start_Date = TVM.Start_Date;
            T.End_Date = TVM.End_Date;
            T.Duration = TVM.Duration;
            T.Description = TVM.Description;
            TVM.Estimation = TVM.Estimation;




            TS.Update(T);
            TS.Commit();
            return RedirectToAction("Index");
        }

        // GET: Task/Delete/5
        public ActionResult Delete(int id)
        {
            return View();

        }

        // POST: Task/Delete/5
        [HttpPost]

        public ActionResult Delete(int id, TaskViewModel TVM)
        {
            Tasks T = TS.GetById(id);

            TVM.TasksId = T.TasksId;
            TVM.TaskName = T.TaskName;
            TVM.Start_Date = T.Start_Date;
            TVM.End_Date = T.End_Date;
            TVM.Duration = T.Duration;
            TVM.Description = T.Description;
            TVM.Estimation = T.Estimation;

            TS.Delete(T);
            TS.Commit();



            return RedirectToAction("Index");
        }
    }
}

Web/Views/Project/Create.cshtml
@model Web.Models.ProjectViewModel

@{

    Layout = "~/Views/Shared/_TeamleaderLayout.cshtml";

}

<div class="container-fluid">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-12">
                <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Create New Project</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                    <li class="breadcrumb-item">Projects</li>
                    <li class="breadcrumb-item active">Add Project</li>
                </ul>
            </div>
            <div class="col-lg-6 col-md-4 col-sm-12 text-right">
                <div class="bh_chart hidden-xs">
                    <div class="float-left m-r-15">
                        <small>Visitors</small>
                        <h6 class="mb-0 mt-1"><i class="icon-user"></i> 1,784</h6>
                    </div>
                    <span class="bh_visitors float-right">2,5,1,8,3,6,7,5</span>
                </div>
                <div class="bh_chart hidden-sm">
                    <div class="float-left m-r-15">
                        <small>Visits</small>
                        <h6 class="mb-0 mt-1"><i class="icon-globe"></i> 325</h6>
                    </div>
                    <span class="bh_visits float-right">10,8,9,3,5,8,5</span>
                </div>
                <div class="bh_chart hidden-sm">
                    <div class="float-left m-r-15">
                        <small>Chats</small>
                        <h6 class="mb-0 mt-1"><i class="icon-bubbles"></i> 13</h6>
                    </div>
                    <span class="bh_chats float-right">1,8,5,6,2,4,3,2</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="row clearfix">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Project Name" } })
                                    @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                                    @*<input type="text" class="form-control" placeholder="Project Name *">*@
                                </div>
                            </div>
                            @*<div class="col-md-3 col-sm-12">
                                    <div class="form-group">
                                        <select class="form-control show-tick">
                                            <option>Select Client Name</option>
                                            <option>Core Technolab Pvt.</option>
                                            <option>vPro Infoweb LLC.</option>
                                            <option>M2 Solution Pvt. Ltd.</option>
                                        </select>
                                    </div>
                                </div>*@
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <div class="input-daterange input-group" data-provide="datepicker">
                                        @Html.EditorFor(model => model.Start_Date, new { htmlAttributes = new { @class = "form-control", @placeholder = "Start Date *", @name = "start" } })
                                        @Html.ValidationMessageFor(model => model.Start_Date, "", new { @class = "text-danger" })
                                        <span class="input-group-addon"> &nbsp; to &nbsp; </span>
                                        @Html.EditorFor(model => model.End_Date, new { htmlAttributes = new { @class = "form-control", @placeholder = "End Date *", @name = "end" } })
                                        @Html.ValidationMessageFor(model => model.End_Date, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            @*<div class="col-md-3 col-sm-12">
                                    <div class="form-group">
                                        @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @placeholder = "Duration" } })
                                        @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                                        @*<select class="form-control show-tick">
                                            <option>Select Priority</option>
                                            <option>High</option>
                                            <option>Medium</option>
                                            <option>Low</option>
                                        </select>
                                    </div>
                                </div>*@
                        </div>
                        @*<div class="row clearfix">
                                @*<div class="col-md-3 col-sm-12">
                                    <label>Select Rate in Doller</label>
                                    <div class="form-group">
                                        <input type="number" class="form-control" placeholder="Rate *">
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-12">
                                    <label>Type</label>
                                    <div class="form-group">
                                        <select class="form-control show-tick">
                                            <option>Select Type</option>
                                            <option>Hourly</option>
                                            <option>Fixed</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-12">
                                    <label>Select Team Lead</label>
                                    <div class="form-group">
                                        <select class="form-control show-tick">
                                            <option>Select</option>
                                            <option>Marshall Nichols</option>
                                            <option>Susie Willis</option>
                                            <option>Hossein Shams</option>
                                            <option>Fidel Tonn</option>
                                            <option>Frank Camly</option>
                                            <option>Debra Stewart</option>
                                            <option>Tim Hank</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-12">
                                    <label>Selet Team</label>
                                    <div class="form-group">
                                        <select id="multiselect3-all" class="multiselect multiselect-custom" multiple="multiple">
                                            <option value="multiselect-all">Select All</option>
                                            <option value="cheese">Cheese</option>
                                            <option value="tomatoes">Tomatoes</option>
                                            <option value="mozarella">Mozzarella</option>
                                            <option value="mushrooms">Mushrooms</option>
                                            <option value="pepperoni">Pepperoni</option>
                                            <option value="onions">Onions</option>
                                        </select>
                                    </div>
                                </div>
                            </div>*@

                        <div class="row clearfix">
                            @*<div class="col-12">
                                    <input type="file" class="dropify">
                                    <div class="mt-3"></div>
                                </div>*@

                            <div class="col-sm-12">
                                <div class="summernote">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="mt-4">
                                    <button type="submit" class="btn btn-primary">Create</button>
                                    <button type="submit" class="btn btn-outline-secondary">Cancel</button>
                                </div>
                                @ViewBag.Message
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Project/Details.cshtml
@model Web.Models.ProjectViewModel
@using Domain.Entities;

@{
    Layout = "~/Views/Shared/_TeamleaderLayout.cshtml";

    IEnumerable<Tasks> tache = ViewData["Tasks"] as IEnumerable<Tasks>;
    var T = (Team)ViewData["Team"];
    var U = (User)ViewData["TeamLead"];
    var progress = ViewData["Progress"];
}

<div class="container-fluid">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-12">
                <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i class="fa fa-arrow-left"></i></a> Project Details</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                    <li class="breadcrumb-item">Projects</li>
                    <li class="breadcrumb-item active">Project Details</li>
                </ul>
            </div>
            <div class="col-lg-6 col-md-4 col-sm-12 text-right">
                <div class="bh_chart hidden-xs">
                    <div class="float-left m-r-15">
                        <small>Visitors</small>
                        <h6 class="mb-0 mt-1"><i class="icon-user"></i> 1,784</h6>
                    </div>
                    <span class="bh_visitors float-right">2,5,1,8,3,6,7,5</span>
                </div>
                <div class="bh_chart hidden-sm">
                    <div class="float-left m-r-15">
                        <small>Visits</small>
                        <h6 class="mb-0 mt-1"><i class="icon-globe"></i> 325</h6>
                    </div>
                    <span class="bh_visits float-right">10,8,9,3,5,8,5</span>
                </div>
                <div class="bh_chart hidden-sm">
                    <div class="float-left m-r-15">
                        <small>Chats</small>
                        <h6 class="mb-0 mt-1"><i class="icon-bubbles"></i> 13</h6>
                    </div>
                    <span class="bh_chats float-right">1,8,5,6,2,4,3,2</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-lg-4 col-md-12">
            <div class="card">
                <div class="body">
                    <h5>  @Html.DisplayFor(model => model.ProjectName)</h5>
                    <p>  @Html.DisplayFor(model => model.Description)</p>
                    <div class="progress-container progress-info m-b-25">
                        <span class="progress-badge">Project Status</span>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: @progress%;">
                                <span class="progress-value">@progress %</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="body">
                    <ul class=" list-unstyled basic-list">
                        <li>Created:<span class="badge-purple badge">  @Html.DisplayFor(model => model.Start_Date)</span></li>
                        <li>Deadline:<span class="badge-danger badge">  @Html.DisplayFor(model => model.End_Date)</span></li>
                        <li>Duration:<span class="badge-warning badge"> @Html.DisplayFor(model => model.Duration) Days</span></li>

                        <li>Status<span class="badge-info badge"> @Html.DisplayFor(model => model.etat)</span></li>
                    </ul>
                </div>
            </div>
            <div class="card">
                <div class="header">
                    <h2>
                        Assigned Team
                        <small>@T.TeamName</small>
                    </h2>
                </div>
                <div class="body">
                    <div class="w_user">
                        <img class="rounded-circle" src="../assets/images/sm/avatar4.jpg" alt="">
                        <div class="wid-u-info">
                            <h5>@U.firstname @U.lastname</h5>
                            <span>@U.Email</span>
                            <p class="text-muted m-b-0">@U.role </p>
                        </div>
                        <hr>
                    </div>
                    <ul class="right_chat list-unstyled mb-0">
                        <li class="online">
                            <a href="javascript:void(0);">
                                <div class="media">
                                    <img class="media-object " src="../assets/images/xs/avatar4.jpg" alt="">
                                    <div class="media-body">
                                        <span class="name">Chris Fox</span>
                                        <span class="message">Sales Lead</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="online">
                            <a href="javascript:void(0);">
                                <div class="media">
                                    <img class="media-object " src="../assets/images/xs/avatar5.jpg" alt="">
                                    <div class="media-body">
                                        <span class="name">Joge Lucky</span>
                                        <span class="message">Java Developer</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="offline">
                            <a href="javascript:void(0);">
                                <div class="media">
                                    <img class="media-object " src="../assets/images/xs/avatar2.jpg" alt="">
                                    <div class="media-body">
                                        <span class="name">Isabella</span>
                                        <span class="message">UI UX Designer</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="offline">
                            <a href="javascript:void(0);">
                                <div class="media mb-0">
                                    <img class="media-object " src="../assets/images/xs/avatar1.jpg" alt="">
                                    <div class="media-body">
                                        <span class="name">Folisise Chosielie</span>
                                        <span class="message">FrontEnd Developer</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card">
                <div class="header">
                    <h2>About Clients</h2>
                </div>
                <div class="body text-center">
                    <div class="profile-image m-b-15"> <img src="../assets/images/user.png" class="rounded-circle" alt=""> </div>
                    <div>
                        <h4 class="m-b-0"><strong>Jessica</strong> Doe</h4>
                        <span>Washington, d.c.</span>
                    </div>
                    <div class="m-t-15">
                        <button class="btn btn-primary">Profile</button>
                        <button class="btn btn-outline-secondary">Message</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-12">
            @*<div class="card">
                    <div class="header">
                        <h2>Project Activity</h2>
                    </div>
                    <div class="body">
                        <div class="form-group">
                            <textarea rows="2" class="form-control no-resize" placeholder="Please type what you want..."></textarea>
                        </div>
                        <div class="post-toolbar-b">
                            <button class="btn btn-warning"><i class="icon-paper-clip text-light"></i></button>
                            <button class="btn btn-warning"><i class="icon-camera text-light"></i></button>
                            <button class="btn btn-primary">Add</button>
                        </div>
                    </div>
                </div>*@
            <div class="card">
                <div class="header">
                    <ul class="header-dropdown">
                        <li><a href="@Url.Action("Create","Task", new { idProject = @Html.DisplayFor(model => model.ProjectId)})"><i class="icon-plus"></i></a></li>
                    </ul>
                </div>
                <div class="body project_report">
                    <div class="table-responsive">
                        <table class="table table-hover js-basic-example dataTable table-custom m-b-0">
                            <thead>
                                <tr>
                                    <th>Task</th>
                                    <th>Deadline</th>
                                    <th>Prograss</th>
                                    <th>Member</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var task in tache)
                                {
                                    <tr>
                                        <td class="project-title">
                                            <h6>@task.TaskName</h6>
                                            <small>Created @task.Start_Date.ToString("dd MMM, yyyy")</small>
                                        </td>
                                        <td>@task.End_Date.ToString("dd MMM, yyyy")</td>
                                        <td>
                                            <div class="progress progress-xs">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="48" aria-valuemin="0" aria-valuemax="100" style="width: 48%;"></div>
                                            </div>
                                            <small>Completion with: 48%</small>
                                        </td>
                                        <td><img src="../assets/images/xs/avatar1.jpg" data-toggle="tooltip" data-placement="top" title="Team Lead" alt="Avatar" class="width35 rounded"></td>
                                        <td><span class="badge badge-success">@task.Status</span></td>
                                        <td class="project-actions">
                                            <a href="@Url.Action("Details","Task", new { id = task.TasksId})" class="btn btn-sm btn-outline-primary"><i class="icon-eye"></i></a>
                                            <a href="@Url.Action("Edit","Task", new { id = task.TasksId})" class="btn btn-sm btn-outline-success"><i class="icon-pencil"></i></a>
                                            <a href="@Url.Action("Delete","Task", new { id = task.TasksId})" class="btn btn-sm btn-outline-danger js-sweetalert" title="Delete" data-type="confirm"><i class="icon-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>